import os
import json
import time
from dotenv import load_dotenv
load_dotenv()
from google import genai

def test_gemini_with_retry():
    gemini_key = os.getenv("GEMINI_API_KEY")
    g_client = genai.Client(api_key=gemini_key)
    
    with open("data/precomputed_stats.json", "r", encoding="utf-8") as f:
        precomputed = json.load(f)
        
    from backend.rag.rag_engine import RAGEngine
    engine = RAGEngine()
    
    matches = engine.vector_store.query_similar("what information do people remember while searching a photo?", n_results=10)
    total_relevant = 916
    key_insights_summary = engine._build_key_insights_summary(precomputed)
    
    from backend.rag.rag_engine import RAG_PROMPT_TEMPLATE
    prompt_input = RAG_PROMPT_TEMPLATE.format(
        prompt="what information do people remember while searching a photo?",
        chat_history_context="None",
        retrieved_context="\n".join([f"[{i+1}] Quote: {m['quote']}" for i, m in enumerate(matches[:5])]),
        total_relevant=total_relevant,
        key_insights_summary=key_insights_summary,
        themes_summary="Face rec failure 18.45%",
        situations_summary="Retrieving Person 11.24%"
    )
    
    for attempt in range(1, 6):
        try:
            print(f"Attempt {attempt}: Calling Gemini 3.6 Flash...")
            resp = g_client.models.generate_content(
                model="gemini-3.6-flash",
                contents=prompt_input
            )
            answer = (resp.text or "").encode("utf-8", errors="ignore").decode("ascii", errors="ignore")
            print("\n=== GROUNDED RAG ANSWER GENERATED BY GEMINI ===")
            print(answer)
            return
        except Exception as e:
            print(f"Attempt {attempt} failed: {e}")
            print("Sleeping 10s before retry...")
            time.sleep(10)

if __name__ == "__main__":
    test_gemini_with_retry()
